spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inspection?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 201409
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      jedis:
        pool:
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10  # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
      timeout: 1000 # 连接超时时间（毫秒）
      host: 47.103.192.12
      port: 6380
      password: 201409

mybatis:
  type-aliases-package: com.wll.inspection.dao
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080


#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


#img:
#  location: E://
#配置上传文件的最大值
servlet:
  multipart:
    max-file-size: 1024MB #限制单个文件的最大值
    max-request-size: 1024MB #限制上传的多个文件的总大小



#自定义文件上传路径
web:
  upload-path: /Downloads/imgUpload/


aliyun-oss:
  #bucket名称
  endpoint: http://oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4G6aok4tEDsh1BDuUmZQ
  accessKeySecret: C97797tAmmfQKn6DF17sIQyQWSdpFO
  bucketName: xunjianxitong